roleGuide: 
  - source: 西风驿站
    collection_id: 
    - 839176
    - 839179
    - 839181
    - 1180811
  - source: 原神观测枢
    collection_id: 
    - 813033
  - source: 派蒙喵喵屋
    collection_id: 
    - 341284
  - source: OH是姜姜呀 # (需特殊处理)
    collection_id: 
    - 341523
  - source: 曉K
    collection_id: 
    - 1582613
  - source: 轻松的蓝色三明治
    collection_id: 
    - 1624518
  - source: 坤易
    collection_id: 
    - 22148